<?php
include '../config/database.php';
require_admin();
$page_title='CRUD Ticket';
$events=db_all("SELECT id_event,title FROM events ORDER BY title");$edit_id=(int)($_GET['edit']??0);$edit=$edit_id?db_one("SELECT * FROM ticket_types WHERE id_ticket=$edit_id"):null;$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
$id=(int)($_POST['id_ticket']??0);$id_event=(int)$_POST['id_event'];$name=$_POST['ticket_name'];$price=(float)$_POST['price'];$quota=(int)$_POST['quota'];$sold=(int)$_POST['sold'];$benefits=trim($_POST['benefits']);
if(!in_array($name,['Regular','VIP','VVIP','Backstage Pass'],true))$errors[]='Jenis tiket tidak valid.'; if($price<1)$errors[]='Harga tidak valid.'; if($quota<1)$errors[]='Quota tidak valid.';
if(!$errors){if($id){$stmt=mysqli_prepare($conn,"UPDATE ticket_types SET id_event=?,ticket_name=?,price=?,quota=?,sold=?,benefits=? WHERE id_ticket=?");mysqli_stmt_bind_param($stmt,'isdiisi',$id_event,$name,$price,$quota,$sold,$benefits,$id);}else{$stmt=mysqli_prepare($conn,"INSERT INTO ticket_types (id_event,ticket_name,price,quota,sold,benefits) VALUES (?,?,?,?,?,?)");mysqli_stmt_bind_param($stmt,'isdiis',$id_event,$name,$price,$quota,$sold,$benefits);}mysqli_stmt_execute($stmt);set_flash('success','Ticket disimpan.');header('Location: '.url('admin/tickets.php'));exit;}}
if(isset($_GET['delete'])){mysqli_query($conn,"DELETE FROM ticket_types WHERE id_ticket=".(int)$_GET['delete']);set_flash('success','Ticket dihapus.');header('Location: '.url('admin/tickets.php'));exit;}
$rows=db_all("SELECT t.*,e.title FROM ticket_types t JOIN events e ON t.id_event=e.id_event ORDER BY e.title,t.price");include '../includes/admin_header.php';show_flash();
?>
<h1 class="admin-title">CRUD Ticket</h1>
<div class="form-card mb-6"><form method="POST" class="crud-form" data-validate-form novalidate><?php validation_box($errors); ?><input type="hidden" name="id_ticket" value="<?= (int)($edit['id_ticket']??0); ?>"><div class="form-grid"><div><label>Event</label><select class="select" name="id_event"><?php foreach($events as $ev): ?><option value="<?= (int)$ev['id_event']; ?>" <?= (($edit['id_event']??'')==$ev['id_event'])?'selected':''; ?>><?= e($ev['title']); ?></option><?php endforeach; ?></select></div><div><label>Ticket Name</label><select class="select" name="ticket_name"><?php foreach(['Regular','VIP','VVIP','Backstage Pass'] as $t): ?><option <?= (($edit['ticket_name']??'')===$t)?'selected':''; ?>><?= e($t); ?></option><?php endforeach; ?></select></div><div><label>Price</label><input class="input" type="number" name="price" value="<?= e($edit['price']??100000); ?>" data-validate data-required="true" data-min-number="1" data-label="Harga"></div><div><label>Quota</label><input class="input" type="number" name="quota" value="<?= e($edit['quota']??100); ?>" data-validate data-required="true" data-min-number="1" data-label="Quota"></div><div><label>Sold</label><input class="input" type="number" name="sold" value="<?= e($edit['sold']??0); ?>" data-validate data-required="true" data-min-number="0" data-label="Sold"></div></div><label>Benefits</label><textarea name="benefits" rows="3" data-validate data-required="true" data-min="5" data-label="Benefits"><?= e($edit['benefits']??'Digital ticket, festival access'); ?></textarea><button class="primary-btn">Simpan Ticket</button></form></div>
<div class="table-wrap"><table><thead><tr><th>Event</th><th>Ticket</th><th>Price</th><th>Quota</th><th>Sold</th><th>Aksi</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= e($r['title']); ?></td><td><?= e($r['ticket_name']); ?></td><td><?= rupiah($r['price']); ?></td><td><?= (int)$r['quota']; ?></td><td><?= (int)$r['sold']; ?></td><td><a class="action-link" href="?edit=<?= (int)$r['id_ticket']; ?>">Edit</a> <a class="action-link" data-confirm="Hapus ticket?" href="?delete=<?= (int)$r['id_ticket']; ?>">Hapus</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php include '../includes/admin_footer.php'; ?>
